# Generated by Django 4.1.2 on 2022-12-22 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='descriptipn',
            new_name='description',
        ),
    ]
